#!/bin/sh

case "$1" in
    start)
        /var/packages/TranscodeDrivers/target/bin/helper/transcode-helper start
        exit 0
        ;;
    stop)
        /var/packages/TranscodeDrivers/target/bin/helper/transcode-helper stop
        exit 0
        ;;
    status)
        /sbin/lsmod | grep -q "^i915 " || exit 3
        exit 0
        ;;
    killall)
        exit 0
        ;;
    log)
        exit 0
        ;;
esac
