- name: Create driver zips
        run: |
          VERSION=${{ github.event.release.tag_name }}
          cd lib
          zip -j ../dsm73_drivers_${VERSION}.zip dsm73/*.ko
          zip -j ../dsm72_drivers_${VERSION}.zip dsm72/*.ko

      - name: Upload to release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ github.event.release.tag_name }}
          gh release upload ${VERSION} \
            dsm73_drivers_${VERSION}.zip \
            dsm72_drivers_${VERSION}.zip
